changeLogFile: changelog/db.changelog-master.yaml
url: jdbc:postgresql://localhost:5432/aurora_ledger
username: liquibase_migrator
password: changeme
driver: org.postgresql.Driver
# liquibase.hub.mode: off
